Rename "types" to "mappings"
Previous version was causing a circular import:

```
  File "/usr/local/lib/python3.12/functools.py", line 22, in <module>
    from types import GenericAlias
ImportError: cannot import name 'GenericAlias' from partially initialized module 'types' (most likely due to a circular import) (/app/types.py)
```

Too many "types" :)